[project]
name = "uc-intg-yamaha-avr"
version = "0.4.7"
description = "An Unfolded Circle integration for Yamaha AV Receivers"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "async-timeout>=5.0.1",
    "pyee~=12.0.0",
    "ucapi==0.3.1",
    "aiohttp>=3.0.0,<4.0.0",
    "ssdp==1.3.0",
    "pyamaha-yec==0.6.3",
    "defusedxml==0.7.1",
    "ssdpy==0.4.1",
]
